"""empty message

Revision ID: c1841c388103
Revises: f408cb866a27
Create Date: 2026-06-05 04:09:07.845576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c1841c388103'
down_revision = 'f408cb866a27'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_col')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_col', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
