"""empty message

Revision ID: d8ed4e43fde8
Revises: 47e4a59493f6
Create Date: 2026-06-05 04:11:48.192544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8ed4e43fde8'
down_revision = '47e4a59493f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_col')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_col', sa.TEXT(), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
